version: '3.4'

services:
  twitchstatsaggdemo:
    image: twitchstatsaggdemo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      SERVER_ADDRESS: 0.0.0.0:3000
    env_file: .env



