openapi: 3.0.4
info:
  title: Twitch Stats Agg Demo
  version: 0.0.1
servers:
  - url: localhost:3000
    description: Local testing URL

paths:
  /streamer/{channelId}/stats:
    get:
      summary: Returns some aggregated engagement stats for the specified streamer
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
          required: true
          description: The number of videos to include in the aggregate
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Stats"
        "404":
          description: No videos found for that user ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Stats:
      type: object
      properties:
        totalViews:
          type: integer
        meanViews:
          type: integer
        totalLength:
          type: integer
        viewsPerMinute:
          type: integer
        mostViewedVideo:
          $ref: "#/components/schemas/User"
      required:
        - totalViews
        - meanViews
        - totalLength
        - viewsPerMinute
        - mostViewedVideo
    Video:
      type: object
      properties:
        title:
          type: string
        views:
          type: integer
    Error:
      type: object
      properties:
        description: string
